name: js
version: 0.4.0-dev.1
authors:
- Dart Team <misc@dartlang.org>
- Alexandre Ardhuin <alexandre.ardhuin@gmail.com>
description: Access JavaScript from Dart.
homepage: https://github.com/dart-lang/js-interop
environment:
  sdk: '>=1.9.0-dev.5.1 <2.0.0'
dependencies:
  browser: '>=0.9.0 <0.11.0'
  source_gen: ^0.3.0
dev_dependencies:
  unittest: '>=0.9.0 <0.12.0'
